#!/bin/bash

#ulimit -S -v 1500000
#{Thu Oct 20 01:39:49 2011}
#ne wenns out of mem dann  wg vector limit auf 32 bit gl
#ulimit -S -v 1000000
#{Tue Jun 25 15:22:41 2013}
#ulimit -S -v 1500000
#{Fri Jul 19 07:27:50 2013} need more man
ulimit -S -v 3500000

exec gsc -:tE,dar,t8,f8,-8 "$@"

