#!/bin/bash

set -euo pipefail
IFS=

usage () {
    echo "usage: $0 packagename testedfilename targetdir"
    echo "  Installs \$packagename via apt,"
    echo "  finds \$testedfilename in \$packagename,"
    echo "  then symlinks the found's file's parent directory to \$targetdir"
    exit 1
}

if [ $# -ne 3 ]; then
    usage
fi

packagename=$1
testedfilename=$2
targetdir=$3

apt-get install -y "$packagename"

# (Note: printf '%q' does not escape e.g. dot, it's not for regular
# expressions.)
pattern="/$(perl -we 'print quotemeta($ARGV[0])' "$testedfilename")$"

#echo "pattern=<$pattern>"

mapfile -t items < <(dpkg -L "$packagename" | egrep -- "$pattern")

if ((${#items[@]} != 1)); then
    echo "$0 $packagename $testedfilename $targetdir: need exactly 1 match for pattern '$pattern', got ${#items[@]}" >&2
    exit 1
fi

set -x
ln -s "$(dirname "${items[0]}")" "$targetdir"
